# Copyright (c) 2011-2023, The DART development contributors
# All rights reserved.

[build-system]
requires = ["setuptools>=42", "wheel", "ninja", "cmake>=3.12"]
build-backend = "setuptools.build_meta"

[tool.isort]
profile = "black"

[tool.mypy]
files = "setup.py"
python_version = "3.7"
strict = true
show_error_codes = true
enable_error_code = ["ignore-without-code", "redundant-expr", "truthy-bool"]
warn_unreachable = true

[[tool.mypy.overrides]]
module = ["ninja"]
ignore_missing_imports = true

[tool.pytest.ini_options]
minversion = "6.0"
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
filterwarnings = ["error"]
testpaths = ["tests"]

# https://cibuildwheel.readthedocs.io/en/stable/options/#before-all
[tool.cibuildwheel]
manylinux-x86_64-image = "dartsim/dart-dev:manylinux2014_x86_64-v7.0"
manylinux-pypy_x86_64-image = "dartsim/dart-dev:manylinux2014_x86_64-v7.0"
test-requires = "pytest"
test-command = "pytest {project}/python/tests"
# https://cibuildwheel.readthedocs.io/en/stable/options/#build-skip
build = [
    # Linux
    "cp38-manylinux_x86_64",
    "cp39-manylinux_x86_64",
    "cp310-manylinux_x86_64",
    "cp311-manylinux_x86_64",

    # macOS
    "cp310-macosx_x86_64",
    "cp311-macosx_x86_64",

    # Windows
    "cp310-win_amd64",
]

[tool.cibuildwheel.linux]
archs = ["auto64"]
environment-pass = ["DART_IN_CI"]

[tool.cibuildwheel.macos]
archs = ["auto64"]
before-all = [
    "brew update > /dev/null",
    "brew bundle || brew bundle",
    "brew install open-scene-graph",
    "sw_vers",
]

[tool.cibuildwheel.windows]
archs = ["auto64"]

[[tool.cibuildwheel.overrides]]
select = "*-musllinux*"
