# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI macOS

on:
  push:
    branches:
      - "**"
  schedule:
    # Cron syntax: [minute hour day_of_the_month month day_of_the_week]
    - cron: "0 2 * * 0,3" # Run every Sunday and Wednesday at 02:00

jobs:
  build:
    runs-on: ${{ matrix.osx_image }}
    strategy:
      fail-fast: false
      matrix:
        build_type: [Release]
        osx_image: [macos-12]
        enable_simd: [ON]
    env:
      COMPILER: clang
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DARTPY: ON
      IN_CI: ON
      ENABLE_SIMD: ${{ matrix.enable_simd }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        env:
          INSTALL_OSG_HEAD: OFF  # To avoid building OSG, until 3.7 is released.
        run: .ci/install_osx.sh
      - name: Build
        run: sudo -E .ci/build.sh
