# https://help.github.com/en/articles/workflow-syntax-for-github-actions

name: CI Windows

on:
  push:
    branches:
      - "**"
  schedule:
    # Cron syntax: [minute hour day_of_the_month month day_of_the_week]
    - cron: "0 2 * * 0,3" # Run every Sunday and Wednesday at 02:00

jobs:
  build_2022:
    name: shared=${{ matrix.build_shared_libs }}.${{ matrix.build_type }}
    runs-on: windows-2022
    strategy:
      fail-fast: false
      matrix:
        toolset: [""]
        build_type: [Release]
        build_shared_libs: [ON, OFF]
        build_dartpy: [OFF]       # Build tests and dartpy exclusively 
                                  # and building dartpy is disabled for now due to the lack of sufficient disk space in the CI
        enable_simd: [ON]
    env:
      VCPKG_BUILD_TAG: v2023.01.16-2
      VCPKG_DEPS_ZIP: vcpkg-dartsim-deps-v7.0.zip
      BUILD_TYPE: ${{ matrix.build_type }}
      BUILD_DARTPY: ${{ matrix.build_dartpy }}
      ENABLE_SIMD: ${{ matrix.enable_simd }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install Dependencies
        shell: cmd
        run: |
          choco install -y wget
          wget -q https://github.com/dartsim/vcpkg-build/releases/download/%VCPKG_BUILD_TAG%/%VCPKG_DEPS_ZIP%
          unzip -qq %VCPKG_DEPS_ZIP% -d C:/.dartsim/
          del %VCPKG_DEPS_ZIP%
      - name: Build and run tests
        if: matrix.build_dartpy == 'OFF'
        shell: cmd
        run: |
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -Wno-dev ${{ matrix.toolset }} ^
            -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
            -DDART_BUILD_DARTPY=%BUILD_DARTPY% ^
            -DCMAKE_TOOLCHAIN_FILE="C:/.dartsim/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
            -DDART_VERBOSE=ON ^
            -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }} ^
            -DDART_BUILD_COMP_gui=OFF ^
            -DDART_IN_CI=ON ^
            -DDART_ENABLE_SIMD=%ENABLE_SIMD%
          cmake --build . --config %BUILD_TYPE% --target tests --parallel
          ctest --rerun-failed --output-on-failure -C %BUILD_TYPE%
      - name: Build dartpy
        if: matrix.build_dartpy == 'ON'
        shell: cmd
        run: |
          python -m pip install --upgrade pip
          pip install -U pytest
          mkdir build
          cd build
          cmake .. -G "Visual Studio 17 2022" -A x64 -Wno-dev ${{ matrix.toolset }} ^
            -DCMAKE_BUILD_TYPE=%BUILD_TYPE% ^
            -DDART_BUILD_DARTPY=%BUILD_DARTPY% ^
            -DCMAKE_TOOLCHAIN_FILE="C:/.dartsim/vcpkg/scripts/buildsystems/vcpkg.cmake" ^
            -DDART_VERBOSE=ON ^
            -DBUILD_SHARED_LIBS=${{ matrix.build_shared_libs }} ^
            -DDART_IN_CI=ON ^
            -DDART_ENABLE_SIMD=%ENABLE_SIMD%
          cmake --build . --config %BUILD_TYPE% --target dartpy --parallel
